import * as T from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {GLTFLoader} from './vendor/GLTFLoader.js';
const $=s=>document.querySelector(s), stage=$('#stage');
const defs=[['Access & lift system',[['canopy','Canopy',0,1],['bay','Internal bay doors',0,1],['lift','Vertical-lift configuration',0,1]]],['Landing gear',[['gear','Retract gear',0,1],['steering','Nose steering',-1,1],['suspension','Suspension compression',0,1],['wheelspin','Wheel rotation',0,1]]],['Flight controls',[['flaps','Flaps',0,1],['rudders','Rudders',-1,1],['stabilizers','Stabilizers',-1,1]]]];
const defaults={canopy:0,bay:0,lift:0,gear:0,steering:0,suspension:0,wheelspin:0,flaps:0,rudders:0,stabilizers:0,fan:0,paint:'#75818c',stores:'training',loadout:'none'};
let state={...defaults}, target={...defaults}, model, tracks={}, rigs=[], gearNodes=[], actuators=[], bySource=new Map(), paintMats=new Set(), tour=null, viewTween=null, spin=0;
for(const [title,fields] of defs){let d=document.createElement('details');d.open=title==='Access & lift system';d.innerHTML=`<summary>${title}</summary>`;for(const [key,label,min,max] of fields){let row=document.createElement('div');row.className='range-row';row.innerHTML=`<label for="${key}">${label}<output id="out-${key}">0%</output></label><input type="range" id="${key}" min="${min}" max="${max}" step="0.01" value="0">`;d.append(row);row.querySelector('input').addEventListener('input',e=>{stopTour();target[key]=Number(e.target.value);syncUI()})}$('#controls').append(d)}
function syncUI(){for(const [,fields] of defs)for(const [k] of fields){$('#'+k).value=target[k];$('#out-'+k).textContent=Math.round(target[k]*100)+'%'}$('#paint').value=target.paint;$('#stores').value=target.stores;$('#loadout').value=target.loadout}
const renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.9;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;stage.prepend(renderer.domElement);
const scene=new T.Scene();scene.background=new T.Color('#151e23');scene.fog=new T.Fog('#151e23',45,95);
const camera=new T.PerspectiveCamera(40,1,.05,150);camera.position.set(-12,8,-15);
const orbit=new OrbitControls(camera,renderer.domElement);orbit.target.set(0,0,0);orbit.enableDamping=true;orbit.dampingFactor=.07;orbit.minDistance=2;orbit.maxDistance=45;orbit.maxPolarAngle=Math.PI*.95;orbit.addEventListener('start',()=>{viewTween=null;stopTour()});
scene.add(new T.HemisphereLight('#d8ecff','#64707a',1.5));
const key=new T.DirectionalLight('#fff0d8',2);key.position.set(-8,15,-8);key.castShadow=true;key.shadow.mapSize.set(1024,1024);Object.assign(key.shadow.camera,{left:-13,right:13,top:13,bottom:-13,near:1,far:50});key.shadow.bias=-.001;key.shadow.normalBias=.035;scene.add(key);
const rim=new T.DirectionalLight('#9fbfff',1);rim.position.set(8,6,12);scene.add(rim);const bellyFill=new T.DirectionalLight('#d5dfe6',1.5);bellyFill.position.set(-3,-9,-5);scene.add(bellyFill);
const floor=new T.Mesh(new T.PlaneGeometry(150,150),new T.MeshStandardMaterial({color:'#253137',roughness:.91}));floor.rotation.x=-Math.PI/2;floor.position.y=-2.205;floor.receiveShadow=true;scene.add(floor);
const grid=new T.GridHelper(80,40,'#425259','#303e44');grid.position.y=-2.202;grid.material.transparent=true;grid.material.opacity=.25;scene.add(grid);
function stripe(x,z,w,l){const o=new T.Mesh(new T.PlaneGeometry(w,l),new T.MeshBasicMaterial({color:'#a4b58b',transparent:true,opacity:.35}));o.rotation.x=-Math.PI/2;o.position.set(x,-2.199,z);scene.add(o)}for(let z=-11;z<=11;z+=2)stripe(0,z,.055,.8);for(const x of [-6.8,6.8])stripe(x,0,.04,18);
new ResizeObserver(()=>{camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix();renderer.setSize(stage.clientWidth,stage.clientHeight)}).observe(stage);
const basis=new T.Quaternion().setFromAxisAngle(new T.Vector3(1,0,0),-Math.PI/2),basisInv=basis.clone().invert();
const vec=a=>new T.Vector3(a[0],a[2],-a[1]);const quat=a=>basis.clone().multiply(new T.Quaternion(...a)).multiply(basisInv);
function initialize(gltf,poses){model=gltf.scene;scene.add(model);tracks=poses;model.traverse(o=>{if(o.userData.source_name)bySource.set(o.userData.source_name,o);o.userData.rest={p:o.position.clone(),q:o.quaternion.clone(),s:o.scale.clone()};if(o.userData.control)rigs.push(o);if(o.userData.gear_pose&&poses[o.userData.gear_pose])gearNodes.push(o);if(o.userData.actuator_start)actuators.push(o);if(o.isMesh){o.castShadow=true;o.receiveShadow=true;for(const m of (Array.isArray(o.material)?o.material:[o.material])){if(/F35D.*(body|panel|edge|radome)/i.test(m.name)){paintMats.add(m);if(!m.userData.original)m.userData.original=m.color.clone()}if(/glass/i.test(m.name)){m.transparent=true;m.opacity=.33;m.depthWrite=false;m.roughness=.15;m.metalness=.12;if('transmission'in m)m.transmission=0;m.side=T.DoubleSide}}}});try{let saved=JSON.parse(localStorage.getItem('hangar01-config'));if(saved){for(const [,fields]of defs)for(const[k,,min,max]of fields)if(Number.isFinite(saved[k]))target[k]=T.MathUtils.clamp(saved[k],min,max);if(/^#[0-9a-f]{6}$/i.test(saved.paint))target.paint=saved.paint;if(['training','display','empty'].includes(saved.stores))target.stores=saved.stores;if(['none','aircraft','hangar'].includes(saved.loadout))target.loadout=saved.loadout}}catch{}state={...target};syncUI();paint(target.paint);applyPose();$('#loading').hidden=true;window.hangarReady=true;$('#message').textContent='Aircraft ready. Drag to explore, or open a mechanism.'}
Promise.all([new GLTFLoader().loadAsync('./assets/f35b-hangar.glb'),fetch('./assets/gear-poses.json').then(r=>{if(!r.ok)throw Error('Pose file unavailable');return r.json()})]).then(([g,p])=>initialize(g,p)).catch(e=>{$('#loading').textContent='Unable to load the aircraft. Start the local server, then reload. '+e.message;console.error(e)});
function applyPose(){if(!model)return;for(const o of rigs){const d=o.userData,r=d.rest,v=state[d.control]||0;o.position.copy(r.p);o.quaternion.copy(r.q);if(d.translation?.some(n=>n!==0))o.position.addScaledVector(vec(d.translation),v);if(d.angle)o.quaternion.multiply(new T.Quaternion().setFromAxisAngle(vec(d.axis).normalize(),d.angle*v))}
 for(const o of gearNodes){const frames=tracks[o.userData.gear_pose],u=T.MathUtils.clamp(state.gear,0,1)*(frames.length-1),i=Math.floor(u),j=Math.min(i+1,frames.length-1),t=u-i,a=frames[i],b=frames[j];o.position.copy(vec(a.p).lerp(vec(b.p),t));o.quaternion.copy(quat(a.q).slerp(quat(b.q),t));o.scale.set(a.s[0]+(b.s[0]-a.s[0])*t,a.s[2]+(b.s[2]-a.s[2])*t,a.s[1]+(b.s[1]-a.s[1])*t)}
 model.updateMatrixWorld(true);for(const o of actuators){const d=o.userData,a=bySource.get(d.actuator_start),b=bySource.get(d.actuator_end);if(!a||!b)continue;let p=a.getWorldPosition(new T.Vector3()),q=b.getWorldPosition(new T.Vector3()),v=q.clone().sub(p),from=p.clone().addScaledVector(v,d.start_fraction);o.parent.worldToLocal(from);o.position.copy(from);let rotation=new T.Quaternion().setFromUnitVectors(new T.Vector3(0,1,0),v.clone().normalize());o.quaternion.copy(o.parent.getWorldQuaternion(new T.Quaternion()).invert().multiply(rotation));o.scale.set(1,v.length()*(d.end_fraction-d.start_fraction),1)}
 model.traverse(o=>{if(o.morphTargetInfluences){let p=o;while(p&&!p.userData.morph_control)p=p.parent;if(p)o.morphTargetInfluences[0]=state[p.userData.morph_control]||0;}if(o.userData.store_set)o.visible=o.userData.store_set===target.stores;if(o.userData.loadout_set)o.visible=o.userData.loadout_set===target.loadout;if(o.userData.hide_when_retracted)o.visible=state.gear<.7});model.updateMatrixWorld(true)}
function paint(hex){target.paint=hex;for(const m of paintMats){m.color.set(hex);const lum=m.userData.original?.getHSL({}).l||.2;m.color.multiplyScalar(T.MathUtils.clamp(lum/.18,.65,1.3))}syncUI()}
$('#paint').addEventListener('input',e=>paint(e.target.value));document.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>paint(b.dataset.color));$('#stores').onchange=e=>{target.stores=e.target.value;$('#message').textContent='Bay contents changed. Open the internal bay doors to inspect.'};$('#loadout').onchange=e=>{target.loadout=e.target.value;$('#message').textContent=({none:'Clean configuration: no external stores.',aircraft:'Stores loaded on the wing hardpoints and centreline.',hangar:'Stores laid out beside the aircraft.'})[target.loadout];if(target.loadout==='hangar')setView('display')};$('#save').onclick=()=>{try{localStorage.setItem('hangar01-config',JSON.stringify(target));$('#message').textContent='Configuration saved in this browser.'}catch{$('#message').textContent='Browser storage is unavailable.'}};
$('#reset').onclick=()=>{stopTour();target={...defaults};$('#orbit').checked=false;$('#fanSpin').checked=false;paint(target.paint);syncUI();setView('hero');$('#message').textContent='Default configuration restored.'};$('#quality').onchange=e=>{const q=e.target.value;renderer.setPixelRatio(Math.min(devicePixelRatio,q==='high'?2:q==='low'?1:1.5));renderer.shadowMap.enabled=q!=='low';renderer.setSize(stage.clientWidth,stage.clientHeight)};
const views={display:{p:[-13,9.5,-19],t:[0,-.6,-3.2]},hero:{p:[-12,8,-15],t:[0,0,0]},top:{p:[-.01,24,.01],t:[0,0,0]},belly:{p:[-12,-11,-17],t:[0,-.5,0]},cockpit:{p:[-3.3,2.8,-8.7],t:[0,.55,-4.7]},rear:{p:[-4,2,12],t:[0,0,5]},fan:{p:[-3.5,6,-1.9],t:[0,.4,-1.6]}};
function setView(name){const v=views[name];if(!v)return;floor.visible=grid.visible=name!=='belly';viewTween={start:performance.now(),p:camera.position.clone(),t:orbit.target.clone(),endP:new T.Vector3(...v.p),endT:new T.Vector3(...v.t)};document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name))}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{stopTour();setView(b.dataset.view)});$('#about').onclick=()=>$('#info').showModal();$('#closeInfo').onclick=()=>$('#info').close();
function stopTour(){tour=null;$('#tour').textContent='▶ Guided walkthrough'}$('#tour').onclick=()=>{if(tour){stopTour();return}target={...defaults,paint:target.paint,stores:target.stores};tour={start:performance.now(),step:-1};$('#tour').textContent='■ Stop walkthrough';setView('hero');syncUI()};
const tourSteps=[{view:'hero',v:{},text:'F-35B · Explore the articulated aircraft.'},{view:'cockpit',v:{canopy:1},text:'Forward-opening canopy and detailed cockpit.'},{view:'belly',v:{bay:1,canopy:0},text:'Internal bays with interchangeable inert display stores.'},{view:'fan',v:{bay:0,lift:1},text:'Lift fan, auxiliary doors and downward nozzle configuration.'},{view:'rear',v:{},text:'Artistic representation of the swiveling rear nozzle.'},{view:'hero',v:{lift:0,gear:1,flaps:.6},text:'Coordinated landing gear stow and movable flight controls.'},{view:'hero',v:{gear:0,flaps:0},text:'Back on its gear. Your turn to explore.'}];
let previous=performance.now(),count=0,lastStats=previous;function animate(now){requestAnimationFrame(animate);let dt=Math.min(.05,(now-previous)/1000);previous=now;if(tour){const step=Math.min(tourSteps.length-1,Math.floor((now-tour.start)/5500));if(step!==tour.step){tour.step=step;const x=tourSteps[step];Object.assign(target,x.v);setView(x.view);syncUI();$('#message').textContent=x.text}if(now-tour.start>tourSteps.length*5500)stopTour()}
 for(const k of Object.keys(defaults))if(typeof defaults[k]==='number')state[k]+=((target[k]||0)-state[k])*Math.min(1,dt*5);if($('#fanSpin').checked&&state.lift>.7){spin+=dt*2;state.fan=spin}else state.fan=0;
 applyPose();if(viewTween){const u=Math.min(1,(now-viewTween.start)/950),e=u*u*(3-2*u);camera.position.lerpVectors(viewTween.p,viewTween.endP,e);orbit.target.lerpVectors(viewTween.t,viewTween.endT,e);if(u===1)viewTween=null}orbit.autoRotate=$('#orbit').checked;orbit.autoRotateSpeed=.55;orbit.update();renderer.render(scene,camera);count++;if(now-lastStats>1500){$('#stats').textContent=`${Math.round(count*1000/(now-lastStats))} FPS · ${Math.round(renderer.info.render.triangles/1000)}K TRIANGLES`;count=0;lastStats=now}}
requestAnimationFrame(animate);
window.hangar={getState:()=>({...target}),setState:v=>{for(const [,fields]of defs)for(const[k,,min,max]of fields)if(Number.isFinite(v[k]))target[k]=T.MathUtils.clamp(v[k],min,max);syncUI()},setView,inspect:()=>({rigs:rigs.length,gearTracks:gearNodes.length,actuators:actuators.length,triangles:renderer.info.render.triangles,drawCalls:renderer.info.render.calls})};
