import * as T from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {GLTFLoader} from './vendor/GLTFLoader.js';
import {applyUV,liveryCanvas} from './livery.js?v=4';
const $=s=>document.querySelector(s), stage=$('#stage');
const defs=[['Access & lift system',[['canopy','Canopy',0,1],['bay','Internal bay doors',0,1],['lift','Vertical-lift configuration',0,1]]],['Landing gear',[['gear','Retract gear',0,1],['steering','Nose steering',-1,1],['suspension','Suspension compression',0,1],['wheelspin','Wheel rotation',0,1]]],['Flight controls',[['flaps','Flaps',0,1],['rudders','Rudders',-1,1],['stabilizers','Stabilizers',-1,1],['nozzle','Nozzle petals',0,1]]],['Display',[['explode','Exploded view',0,3]]]];
const defaults={canopy:0,bay:0,lift:0,gear:0,steering:0,suspension:0,wheelspin:0,flaps:0,rudders:0,stabilizers:0,nozzle:0,explode:0,fan:0,paint:'#75818c',stores:'training',loadout:'none',livery:'none'};
let state={...defaults}, target={...defaults}, model, tracks={}, rigs=[], gearNodes=[], actuators=[], bySource=new Map(), paintMats=new Set(), tour=null, viewTween=null, spin=0;
for(const [,fields] of defs)for(const [key] of fields)$('#'+key).addEventListener('input',e=>{stopTour();target[key]=Number(e.target.value);syncUI()});
function syncUI(){for(const [,fields] of defs)for(const [k] of fields){$('#'+k).value=target[k];$('#out-'+k).textContent=Math.round(target[k]*100)+'%'}$('#paint').value=target.paint;$('#stores').value=target.stores;$('#loadout').value=target.loadout;$('#livery').value=target.livery}
const renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.9;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;stage.prepend(renderer.domElement);
const scene=new T.Scene();scene.background=new T.Color('#151e23');scene.fog=new T.Fog('#151e23',45,95);
{const c=document.createElement('canvas');c.width=1024;c.height=512;const g=c.getContext('2d'),gr=g.createLinearGradient(0,0,0,512);gr.addColorStop(0,'#c3d0dc');gr.addColorStop(.42,'#6c7a87');gr.addColorStop(.5,'#2a3238');gr.addColorStop(1,'#14191c');g.fillStyle=gr;g.fillRect(0,0,1024,512);g.fillStyle='#ffffff';for(let i=0;i<8;i++)g.fillRect(30+i*128,50,84,26);g.fillStyle='#fff0d2';g.fillRect(160,120,280,56);g.fillStyle='#d6e4ff';g.fillRect(690,140,200,46);const t=new T.CanvasTexture(c);t.mapping=T.EquirectangularReflectionMapping;t.colorSpace=T.SRGBColorSpace;const pm=new T.PMREMGenerator(renderer);scene.environment=pm.fromEquirectangular(t).texture;scene.environmentIntensity=1.1;t.dispose();pm.dispose()}
const camera=new T.PerspectiveCamera(40,1,.05,150);camera.position.set(-12,8,-15);
const orbit=new OrbitControls(camera,renderer.domElement);orbit.target.set(0,0,0);orbit.enableDamping=true;orbit.dampingFactor=.07;orbit.minDistance=2;orbit.maxDistance=85;orbit.maxPolarAngle=Math.PI*.95;orbit.addEventListener('start',()=>{viewTween=null;stopTour()});
scene.add(new T.HemisphereLight('#d8ecff','#64707a',1.5));
const key=new T.DirectionalLight('#fff0d8',2);key.position.set(-8,15,-8);key.castShadow=true;key.shadow.mapSize.set(1024,1024);Object.assign(key.shadow.camera,{left:-13,right:13,top:13,bottom:-13,near:1,far:50});key.shadow.bias=-.001;key.shadow.normalBias=.035;scene.add(key);
const rim=new T.DirectionalLight('#9fbfff',1);rim.position.set(8,6,12);scene.add(rim);const bellyFill=new T.DirectionalLight('#d5dfe6',1.5);bellyFill.position.set(-3,-9,-5);scene.add(bellyFill);
const floor=new T.Mesh(new T.PlaneGeometry(150,150),new T.MeshStandardMaterial({color:'#253137',roughness:.91,envMapIntensity:.25}));floor.rotation.x=-Math.PI/2;floor.position.y=-2.205;floor.receiveShadow=true;scene.add(floor);
const grid=new T.GridHelper(80,40,'#425259','#303e44');grid.position.y=-2.202;grid.material.transparent=true;grid.material.opacity=.25;scene.add(grid);
function stripe(x,z,w,l){const o=new T.Mesh(new T.PlaneGeometry(w,l),new T.MeshBasicMaterial({color:'#a4b58b',transparent:true,opacity:.35}));o.rotation.x=-Math.PI/2;o.position.set(x,-2.199,z);scene.add(o)}for(let z=-11;z<=11;z+=2)stripe(0,z,.055,.8);for(const x of [-6.8,6.8])stripe(x,0,.04,18);
new ResizeObserver(()=>{camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix();renderer.setSize(stage.clientWidth,stage.clientHeight)}).observe(stage);
const basis=new T.Quaternion().setFromAxisAngle(new T.Vector3(1,0,0),-Math.PI/2),basisInv=basis.clone().invert();
const vec=a=>new T.Vector3(a[0],a[2],-a[1]);const quat=a=>basis.clone().multiply(new T.Quaternion(...a)).multiply(basisInv);
function initialize(gltf,poses){model=gltf.scene;scene.add(model);tracks=poses;model.traverse(o=>{if(o.userData.source_name)bySource.set(o.userData.source_name,o);o.userData.rest={p:o.position.clone(),q:o.quaternion.clone(),s:o.scale.clone()};if(o.userData.control)rigs.push(o);if(o.userData.gear_pose&&poses[o.userData.gear_pose])gearNodes.push(o);if(o.userData.actuator_start)actuators.push(o);if(o.isMesh){o.castShadow=true;o.receiveShadow=true;for(const m of (Array.isArray(o.material)?o.material:[o.material])){if(/F35D.*(body|panel|edge|radome)/i.test(m.name)){paintMats.add(m);m.metalness=.55;m.roughness=.52;if(!m.userData.original)m.userData.original=m.color.clone()}if(/glass/i.test(m.name)){m.transparent=true;m.opacity=.33;m.depthWrite=false;m.roughness=.15;m.metalness=.12;if('transmission'in m)m.transmission=0;m.side=T.DoubleSide}}}});applyUV(T,model,paintMats);initExplode();initNozzle();try{let saved=JSON.parse(localStorage.getItem('hangar01-config'));if(saved){for(const [,fields]of defs)for(const[k,,min,max]of fields)if(Number.isFinite(saved[k]))target[k]=T.MathUtils.clamp(saved[k],min,max);if(/^#[0-9a-f]{6}$/i.test(saved.paint))target.paint=saved.paint;if(['training','display','empty'].includes(saved.stores))target.stores=saved.stores;if(['none','aircraft','hangar'].includes(saved.loadout))target.loadout=saved.loadout;if(['none','usaf','usmc'].includes(saved.livery))target.livery=saved.livery}}catch{}state={...target};syncUI();paint(target.paint);if(target.livery!=='none')setLivery(target.livery);applyPose();$('#loading').hidden=true;window.hangarReady=true;$('#message').textContent='Aircraft ready. Drag to explore, or open a mechanism.'}
Promise.all([new GLTFLoader().loadAsync('./assets/f35b-hangar-x3.glb'),fetch('./assets/gear-poses.json').then(r=>{if(!r.ok)throw Error('Pose file unavailable');return r.json()})]).then(([g,p])=>initialize(g,p)).catch(e=>{$('#loading').textContent='Unable to load the aircraft. Start the local server, then reload. '+e.message;console.error(e)});
const LIFTS=[0,3.2,3.6,3.9];
function xMir(o){for(const k of Object.keys(o)){const m=k.match(/^(.*)R([io]?)$/);if(m&&!((m[1]+'L'+m[2]) in o)){const v=o[k];o[m[1]+'L'+m[2]]=typeof v[0]==='number'?[-v[0],v[1],v[2]]:v}}return o}
const XV=[null,
{fuselage:[0,0,0],canopy:[0,.9,2.7],seat:[0,-.2,1.35],wingR:[2.6,0,0],wingL:[-2.6,0,0],tailR:[1.7,-1.9,0],tailL:[-1.7,-1.9,0],finR:[1.3,-.5,1.9],finL:[-1.3,-.5,1.9],liftdoor:[0,0,2.5],fan1:[0,0,1.7],fan2:[0,0,.95],aux:[0,-.3,1.2],exit:[0,0,-1.1],nozzle:[0,-2.1,0],bayR:[.55,0,-1.2],bayL:[-.55,0,-1.2],baystores:[0,0,-2.1],gearN:[0,.7,-1.5],gearR:[1.0,0,-1.5],gearL:[-1.0,0,-1.5],extR:[2.6,0,-1.0],extL:[-2.6,0,-1.0],pod:[0,.4,-2.9]},
xMir({canopy:[0,.9,3.2],glass:[0,.9,3.95],seat:[0,-.2,2.2],cockpit:[0,.5,1.25],wingR:[3,0,0],lefR:[3,.8,0],flapR:[3,-.8,0],rpdoorR:[3,0,-.6],tailR:[1.9,-2.1,0],tailtrR:[1.9,-2.8,0],finR:[1.5,-.5,2.3],rudR:[1.5,-1.3,2.3],liftdoor:[0,0,3.5],fan1:[0,0,2.6],fan2:[0,0,1.7],aux:[0,-.3,2.5],exitR:[.5,0,-1.1],nozzle:[0,-1.6,1.7],duct3:[0,-.8,1.7],engine:[0,0,1.7],drive:[0,0,1.7],rollducts:[0,0,1.7],bayRi:[.35,0,-1.3],bayRo:[1,0,-1.3],bstoreR:[.45,0,-2.2],wheelN:[0,.7,-2.2],wheelR:[1,0,-2.2],gdoorN:[0,.35,-.75],gdoorR:[.5,0,-.75],eots:[0,.3,-.8],antenna:[0,0,.8],extR:[3,0,-1],pylR:[3,0,-.5],wpnR:[3,0,-1.3],radome:[0,1.5,0],radar:[0,.7,0]}),
xMir({fusF:[0,1.4,0],radome:[0,3.6,0],rarray:[0,2.9,0],rback:[0,2.2,0],canopy:[0,2.3,4],glass:[0,2.3,4.8],clatch:[0,2.3,3.5],seat:[0,1.2,2.2],seatsoft:[0,1.2,3],cpanel:[0,2.6,1.4],cconsole:[0,1.9,1.1],cctrl:[0,1.9,1.75],eots:[0,1.7,-.8],gdoorN:[0,1.75,-.75],gearN:[0,2.1,-1.5],braceN:[0,2.7,-1.5],lampN:[0,1.5,-1.2],pistonN:[0,2.1,-1.9],forkN:[0,2.1,-2.3],wheelN:[0,2.1,-2.75],tireN:[.5,2.1,-2.75],
 fusA:[0,-1.4,0],tailR:[1.9,-3.5,0],tailtrR:[1.9,-4.2,0],finR:[1.5,-1.9,2.3],rudR:[1.5,-2.7,2.3],
 eigv:[0,0,1.7],efan:[0,-.45,1.7],ecomp:[0,-.9,1.7],ecomb:[0,-1.35,1.7],eturb:[0,-1.8,1.7],eaug:[0,-2.25,1.7],duct3:[0,-2.9,1.7],nozzle:[0,-3.4,1.7],ncollar:[0,-3.4,1.7],npetal:[0,-3.8,1.7],nliner:[0,-4.3,1.7],
 rfan1:[0,-.17,2.75],rfan2:[0,-.45,2.75],rfan3:[0,-.73,2.75],rcomp:[0,-.9,2.75],rcomb:[0,-1.35,2.75],rhpt:[0,-1.7,2.75],rlpt:[0,-2.05,2.75],raug:[0,-2.25,2.75],
 sfan:[1.15,-.45,2.2],scomp:[1.15,-.9,2.2],finj:[1.15,-1.35,2.2],ign:[1.15,-1.35,2.95],sturb:[1.15,-1.8,2.2],spray:[1.15,-2.25,2.2],agb:[1.15,-.9,1.6],fadec:[1.15,-.45,1.6],
 lpshaft:[-1.15,-.9,2.2],augliner:[-1.15,-2.25,2.2],pipes:[-1.15,-.9,1.35],
 dshaft:[0,0,1.7],clutch:[0,0,1.7],cplates:[0,0,2.25],lfgear:[0,0,2.15],vanebox:[0,0,-.6],auxR:[.75,-.3,2.5],
 fairR:[3,0,-.4],rpostR:[3,0,-.35],rpdoorR:[3,0,-.8],braceR:[1,-.55,-1.5],pistonR:[1,0,-1.95],linkR:[1,.5,-1.95],wheelR:[1,0,-2.45],tireR:[1.6,0,-2.45],wpn1R:[3,0,-1.5],wpn2R:[3.3,0,-1.5],wpn3R:[3.6,0,-1.5]})];
const XSYS=[['all','All systems'],['prop','Propulsion'],['lift','Lift system'],['crew','Crew station'],['air','Airframe'],['wing','Wings'],['gear','Landing gear'],['wpn','Weapons']];
const XINFO=xMir({fuselage:['Fuselage and inlets','air'],canopy:['Canopy','crew'],seat:['Ejection seat','crew'],wingR:['Right wing','wing'],wingL:['Left wing','wing'],tailR:['Right horizontal tail','air'],tailL:['Left horizontal tail','air'],finR:['Right fin and rudder','air'],finL:['Left fin and rudder','air'],liftdoor:['Lift fan door','lift'],fan1:['Lift fan, upper stage','lift'],fan2:['Lift fan, lower stage','lift'],aux:['Auxiliary inlet doors','lift'],exit:['Lift fan exit doors','lift'],nozzle:['Swivel nozzle','prop'],bayR:['Right weapons bay doors','wpn'],bayL:['Left weapons bay doors','wpn'],baystores:['Bay stores','wpn'],gearN:['Nose gear','gear'],gearR:['Right main gear','gear'],gearL:['Left main gear','gear'],extR:['Right wing stores','wpn'],extL:['Left wing stores','wpn'],pod:['Gun pod','wpn'],
 glass:['Canopy transparency','crew'],cockpit:['Cockpit instruments','crew'],lefR:['Leading-edge flap','wing'],flapR:['Flaperon','wing'],rpdoorR:['Roll post door','lift'],tailtrR:['Tail trailing section','air'],rudR:['Rudder','air'],exitR:['Exit door','lift'],duct3:['Swivel duct segment','prop'],engine:['F135 engine','prop'],drive:['Drive shaft and clutch','lift'],rollducts:['Roll post ducts','lift'],bayRi:['Inner bay door','wpn'],bayRo:['Outer bay door','wpn'],bstoreR:['Bay store','wpn'],wheelN:['Nose wheel','gear'],wheelR:['Main wheel','gear'],gdoorN:['Nose gear doors','gear'],gdoorR:['Main gear doors','gear'],eots:['Chin sensor (EOTS)','air'],antenna:['Dorsal antenna','air'],pylR:['Pylons','wpn'],wpnR:['Wing weapons','wpn'],radome:['Radome','air'],radar:['AESA radar','air'],
 fusF:['Forward fuselage','air'],fusC:['Centre fuselage','air'],fusA:['Aft fuselage','air'],rarray:['Radar array','air'],rback:['Radar processor','air'],clatch:['Canopy latches and rails','crew'],seatsoft:['Cushions and harness','crew'],cpanel:['Instrument panel','crew'],cconsole:['Side consoles','crew'],cctrl:['Stick and pedals','crew'],
 eigv:['Inlet guide vanes','prop'],efan:['Fan case','prop'],ecomp:['Compressor case','prop'],ecomb:['Combustor case','prop'],eturb:['Turbine case','prop'],eaug:['Augmentor duct','prop'],rfan1:['Fan stage 1','prop'],rfan2:['Fan stage 2','prop'],rfan3:['Fan stage 3','prop'],rcomp:['HP compressor rotor','prop'],rcomb:['Combustor liner','prop'],rhpt:['HP turbine','prop'],rlpt:['LP turbine','prop'],raug:['Flameholder','prop'],sfan:['Fan stators','prop'],scomp:['Compressor stators','prop'],finj:['Fuel injectors','prop'],ign:['Igniters','prop'],sturb:['Nozzle guide vanes','prop'],spray:['Spray bars','prop'],agb:['Accessory gearbox','prop'],fadec:['FADEC','prop'],lpshaft:['LP shaft and bearings','prop'],augliner:['Augmentor liner','prop'],pipes:['Fuel and oil lines','prop'],ncollar:['Nozzle collar','prop'],npetal:['Nozzle petals','prop'],nliner:['Nozzle liner','prop'],
 dshaft:['Drive shaft','lift'],clutch:['Clutch housing','lift'],cplates:['Clutch plates','lift'],lfgear:['Bevel gearbox','lift'],vanebox:['Exit vane box','lift'],auxR:['Auxiliary door','lift'],fanhub1:['Fan hub','lift'],fanhub2:['Fan hub','lift'],fanbl1:['Fan blades','lift'],fanbl2:['Fan blades','lift'],
 fairR:['Hinge fairings','wing'],rpostR:['Roll post outlet','lift'],tireR:['Tyre','gear'],tireN:['Tyre','gear'],braceR:['Drag braces','gear'],braceN:['Drag braces','gear'],pistonR:['Piston and axle','gear'],pistonN:['Shock strut','gear'],linkR:['Torque links','gear'],forkN:['Fork and axle','gear'],lampN:['Landing lamp','gear'],wpn1R:['Inboard bomb','wpn'],wpn2R:['Mid bomb','wpn'],wpn3R:['Wingtip missile','wpn']});
let xAuto=false,xNodes=[],xLabels=[],xShow=true,xLast=0,xSys='all';const xTmp=new T.Vector3(),xTmp2=new T.Vector3(),xM=new T.Matrix4(),xM3=new T.Matrix3();
function xTriple(o){const d=o.userData;return d.xg1?[d.xg1,d.xg2||d.xg1,d.xg3||d.xg2||d.xg1]:null}
function xDisp(tr,d){const out=[new T.Vector3()];let v=[0,0,0];for(let l=1;l<=3;l++){const e=XV[l][tr[l-1]];if(e)v=e;const p=vec([v[0],v[1],v[2]+LIFTS[l]]);if(d){if(l>=2&&d.xo2)p.add(vec(d.xo2));if(l>=3&&d.xo3)p.add(vec(d.xo3))}out.push(p)}return out}
function xAt(d,ex,out){const i=Math.min(3,Math.floor(ex)),j=Math.min(3,i+1);return out.copy(d[i]).lerp(d[j],ex-i)}
function initExplode(){const gearSet=new Set(gearNodes),G=[null,{},{},{}];model.updateMatrixWorld(true);model.traverse(o=>{const tr=xTriple(o);if(!tr)return;const d=o.userData,pt=o.parent&&xTriple(o.parent);d.xd=xDisp(tr,d);if(!pt||pt.join()!==tr.join()||d.xo2||d.xo3){d.xpd=pt?o.parent.userData.xd:null;d.xfree=!d.control&&!gearSet.has(o);xNodes.push(o)}
  const own=[];if(o.isMesh)own.push(o);for(const c of o.children)if(c.isMesh&&!c.userData.xg1)own.push(c);if(!own.length)return;const box=new T.Box3();for(const m of own)box.union(new T.Box3().setFromObject(m));if(box.isEmpty())return;const c=box.getCenter(new T.Vector3());for(let l=1;l<=3;l++)(G[l][tr[l-1]]||(G[l][tr[l-1]]=[])).push({o,c,xd:d.xd})});
 const host=$('#xlabels'),seen=new Set();for(let l=1;l<=3;l++)for(const g of Object.keys(G[l])){if(seen.has(g))continue;seen.add(g);const inf=XINFO[g];if(!inf)continue;const mem=G[l][g],A=[0,1,2,3].map(L=>{const p=new T.Vector3();for(const m of mem)p.add(m.c).add(m.xd[L]);return p.multiplyScalar(1/mem.length)});const el=document.createElement('div');el.className='xl t'+l;el.innerHTML='<i></i><span></span>';el.lastChild.textContent=inf[0];host.append(el);const cw=l===1?6.65:l===2?6.05:5.45;xLabels.push({el,A,lvl:l,sys:inf[1],name:inf[0],pair:g.replace(/[RL]([io]?)$/,'$1')+'|'+inf[0],nodes:mem.map(m=>m.o),w:inf[0].length*cw+(l===3?6:14),hgt:l===1?18:l===2?16:14,mode:''})}
 const sh=$('#xSys');for(const [k,n] of XSYS){const b=document.createElement('button');b.textContent=n;b.dataset.sys=k;b.setAttribute('aria-pressed',String(k===xSys));b.onclick=()=>{xSys=k;for(const x of sh.children)x.setAttribute('aria-pressed',String(x.dataset.sys===k));xFrame()};sh.append(b)}}
function xFrame(){const lv=Math.min(3,Math.max(1,Math.round(target.explode)));if(xSys==='all'){setView('exploded');return}const box=new T.Box3();for(const L of xLabels)if(L.sys===xSys&&L.lvl<=lv)box.expandByPoint(L.A[lv]);if(box.isEmpty())return;const c=box.getCenter(new T.Vector3()),r=Math.max(1.6,box.getSize(new T.Vector3()).length()/2+1.1),asp=stage.clientWidth/stage.clientHeight,half=T.MathUtils.degToRad(camera.fov/2),fit=Math.min(half,Math.atan(Math.tan(half)*asp)),dist=Math.min(orbit.maxDistance,r/Math.sin(fit)),dv={prop:[-.93,.3,-.2],lift:[-.75,.5,-.42],crew:[-.8,.35,-.5],gear:[-.7,-.12,-.7],wpn:[-.6,-.3,-.74]}[xSys]||[-.62,.42,-.66],dir=new T.Vector3(...dv).normalize();viewTween={start:performance.now(),p:camera.position.clone(),t:orbit.target.clone(),endP:c.clone().addScaledVector(dir,dist),endT:c};document.querySelectorAll('[data-view]').forEach(b=>b.classList.remove('active'))}
function shown(o){for(;o;o=o.parent)if(!o.visible)return false;return true}
function applyExplode(){const ex=state.explode||0;if(ex<1e-4&&xLast<1e-4)return;xLast=ex;for(const o of xNodes){const d=o.userData;xAt(d.xd,ex,xTmp);if(d.xpd)xTmp.sub(xAt(d.xpd,ex,xTmp2));if(d.xfree)o.position.copy(d.rest.p);if(o.parent!==model&&xTmp.lengthSq()>1e-10){o.parent.updateWorldMatrix(true,false);xM.copy(model.matrixWorld).invert().multiply(o.parent.matrixWorld);xM3.setFromMatrix4(xM).invert();xTmp.applyMatrix3(xM3)}o.position.add(xTmp)}}
function xMode(L,m){if(L.mode!==m){L.mode=m;L.el.style.display=m?'':'none';if(m)L.el.classList.toggle('dot',m==='dot')}}
function drawLabels(){const ex=state.explode||0,lv=Math.min(3,Math.max(1,Math.round(ex))),a=!xShow?0:ex<1?Math.min(1,Math.max(0,(ex-.45)/.35)):Math.min(1,Math.max(0,1.25-Math.abs(ex-lv)*3)),host=$('#xlabels');if(a<=0){if(!host.hidden)host.hidden=true;return}host.hidden=false;host.style.opacity=a;const w=stage.clientWidth,hh=stage.clientHeight,vis=[],near={};
 for(const L of xLabels){let want=L.lvl>lv?'':xSys==='all'?(L.lvl===1?'text':'dot'):L.sys===xSys?'text':'';if(want){xAt(L.A,ex,xTmp).project(camera);if(!(xTmp.z<1&&Math.abs(xTmp.x)<1.02&&Math.abs(xTmp.y)<1.02&&L.nodes.some(shown)))want=''}if(!want){xMode(L,'');continue}L.x=(xTmp.x+1)/2*w;L.y=(1-xTmp.y)/2*hh;L.z=xTmp.z;L.want=want;if(want==='text'&&xSys!=='all'&&L.lvl>1){const n=near[L.pair];if(!n||L.z<n.z)near[L.pair]=L}vis.push(L)}
 for(const L of vis)if(L.want==='text'&&xSys!=='all'&&L.lvl>1&&near[L.pair]!==L)L.want='dot';
 vis.sort((p,q)=>p.lvl-q.lvl||q.y-p.y);const placed=[];for(const L of vis){let h=L.lvl===3?16:24,mode=L.want;if(mode==='text'){const cx=Math.min(Math.max(L.x,L.w/2+6),Math.max(L.w/2+6,w-L.w/2-6)),l=cx-L.w/2-3,r=cx+L.w/2+3;let n=0;for(;n<9;n++){const t=L.y-h-2-L.hgt,b=L.y-h-2;if(!placed.some(P=>l<P.r&&r>P.l&&t<P.b+3&&b>P.t-3))break;h+=L.hgt+5}if(n>=9||L.y-h-L.hgt<46)mode='dot';else{placed.push({l,r,t:L.y-h-2-L.hgt,b:L.y-h-2});L.el.style.setProperty('--dx',(cx-L.x).toFixed(1)+'px')}}xMode(L,mode);L.el.style.setProperty('--h',(mode==='dot'?16:h)+'px');L.el.style.transform=`translate(${L.x.toFixed(1)}px,${L.y.toFixed(1)}px)`}}
let petals=[],nzLiner=[],nzLast=-1;
function initNozzle(){model.traverse(o=>{const d=o.userData;if(o.isMesh&&String(d.source_name||'').startsWith('Exhaust | overlapping petal')){o.geometry.computeBoundingBox();const b=o.geometry.boundingBox,cx=(b.min.x+b.max.x)/2,cy=(b.min.y+b.max.y)/2,r=new T.Vector3(cx,cy,0).normalize();d.pet={h:new T.Vector3(cx,cy,b.min.z),a:r.clone().cross(new T.Vector3(0,0,1)).normalize(),L:b.max.z-b.min.z};d.xfree=false;petals.push(o)}});
 if(!petals.length)return;const P=petals[0],zh=P.localToWorld(P.userData.pet.h.clone()).z;model.traverse(o=>{if(o.userData.xg3!=='nliner')return;for(const m of o.isMesh?[o]:o.children.filter(c=>c.isMesh)){const pos=m.geometry.attributes.position,src=pos.array.slice();m.geometry.computeBoundingBox();const b=m.geometry.boundingBox;m.updateWorldMatrix(true,false);const z0=m.worldToLocal(new T.Vector3(0,0,zh)).z;nzLiner.push({pos,src,cx:(b.min.x+b.max.x)/2,cy:(b.min.y+b.max.y)/2,z0,z1:b.max.z})}})}
const nzQ=new T.Quaternion(),nzV=new T.Vector3();
function applyNozzle(){const v=state.nozzle||0;for(const o of petals){const d=o.userData,k=d.pet;nzQ.setFromAxisAngle(k.a,v*.25);o.quaternion.copy(d.rest.q).multiply(nzQ);nzV.copy(k.h).applyQuaternion(nzQ).sub(k.h).negate().applyQuaternion(d.rest.q);o.position.copy(d.rest.p).add(nzV)}
 if(Math.abs(v-nzLast)<2e-4)return;nzLast=v;for(const L of nzLiner){const a=L.pos.array,s=L.src;for(let i=0;i<a.length;i+=3){const t=Math.min(1,Math.max(0,(s[i+2]-L.z0)/(L.z1-L.z0))),f=1-v*.21*t;a[i]=L.cx+(s[i]-L.cx)*f;a[i+1]=L.cy+(s[i+1]-L.cy)*f}L.pos.needsUpdate=true}}
function applyPose(){if(!model)return;for(const o of rigs){const d=o.userData,r=d.rest,v=state[d.control]||0;o.position.copy(r.p);o.quaternion.copy(r.q);if(d.translation?.some(n=>n!==0))o.position.addScaledVector(vec(d.translation),v);if(d.angle)o.quaternion.multiply(new T.Quaternion().setFromAxisAngle(vec(d.axis).normalize(),d.angle*v))}
 for(const o of gearNodes){const frames=tracks[o.userData.gear_pose],u=T.MathUtils.clamp(state.gear,0,1)*(frames.length-1),i=Math.floor(u),j=Math.min(i+1,frames.length-1),t=u-i,a=frames[i],b=frames[j];o.position.copy(vec(a.p).lerp(vec(b.p),t));o.quaternion.copy(quat(a.q).slerp(quat(b.q),t));o.scale.set(a.s[0]+(b.s[0]-a.s[0])*t,a.s[2]+(b.s[2]-a.s[2])*t,a.s[1]+(b.s[1]-a.s[1])*t)}
 applyNozzle();applyExplode();
 model.updateMatrixWorld(true);for(const o of actuators){const d=o.userData,a=bySource.get(d.actuator_start),b=bySource.get(d.actuator_end);if(!a||!b)continue;let p=a.getWorldPosition(new T.Vector3()),q=b.getWorldPosition(new T.Vector3()),v=q.clone().sub(p),from=p.clone().addScaledVector(v,d.start_fraction);o.parent.worldToLocal(from);o.position.copy(from);let rotation=new T.Quaternion().setFromUnitVectors(new T.Vector3(0,1,0),v.clone().normalize());o.quaternion.copy(o.parent.getWorldQuaternion(new T.Quaternion()).invert().multiply(rotation));o.scale.set(1,v.length()*(d.end_fraction-d.start_fraction),1)}
 model.traverse(o=>{if(o.morphTargetInfluences){let p=o;while(p&&!p.userData.morph_control)p=p.parent;if(p)o.morphTargetInfluences[0]=state[p.userData.morph_control]||0;}if(o.userData.store_set)o.visible=o.userData.store_set===target.stores;if(o.userData.loadout_set)o.visible=o.userData.loadout_set===target.loadout;if(o.userData.hide_when_retracted)o.visible=state.gear<.7;if(o.userData.x_min!=null||o.userData.x_max!=null){const ex=state.explode||0;o.visible=ex>(o.userData.x_min??-1)&&ex<(o.userData.x_max??99)}});model.updateMatrixWorld(true)}
const livTex={};async function setLivery(v){target.livery=v;if(v!=='none'&&!livTex[v]){const t=new T.CanvasTexture(await liveryCanvas(v,innerWidth<900?80:128));t.colorSpace=T.SRGBColorSpace;t.anisotropy=renderer.capabilities.getMaxAnisotropy();livTex[v]=t}paint(target.paint)}
function paint(hex){target.paint=hex;const L=livTex[target.livery]||null;for(const m of paintMats){if(m.map!==L){m.map=L;m.needsUpdate=true}if(L){m.color.set('#ffffff');continue}m.color.set(hex);const lum=m.userData.original?.getHSL({}).l||.2;m.color.multiplyScalar(T.MathUtils.clamp(lum/.18,.65,1.3))}syncUI()}
$('#paint').addEventListener('input',e=>{target.livery='none';paint(e.target.value)});document.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{target.livery='none';paint(b.dataset.color)});$('#livery').onchange=e=>{setLivery(e.target.value);$('#message').textContent=({none:'Plain finish.',usaf:'U.S. Air Force scheme applied.',usmc:'U.S. Marine Corps scheme applied.'})[e.target.value]};$('#stores').onchange=e=>{target.stores=e.target.value;$('#message').textContent='Bay contents changed. Open the internal bay doors to inspect.'};$('#loadout').onchange=e=>{target.loadout=e.target.value;$('#message').textContent=({none:'Clean configuration: no external stores.',aircraft:'Stores loaded on the wing hardpoints and centreline.',hangar:'Stores laid out beside the aircraft.'})[target.loadout];if(target.loadout==='hangar')setView('display')};$('#save').onclick=()=>{try{localStorage.setItem('hangar01-config',JSON.stringify(target));$('#message').textContent='Configuration saved in this browser.'}catch{$('#message').textContent='Browser storage is unavailable.'}};
$('#reset').onclick=()=>{stopTour();target={...defaults};$('#orbit').checked=false;$('#fanSpin').checked=false;paint(target.paint);syncUI();setView('hero');$('#message').textContent='Default configuration restored.'};$('#quality').onchange=e=>{const q=e.target.value;renderer.setPixelRatio(Math.min(devicePixelRatio,q==='high'?2:q==='low'?1:1.5));renderer.shadowMap.enabled=q!=='low';renderer.setSize(stage.clientWidth,stage.clientHeight)};
const XVIEW={rear:{p:[-8,8.5,17],t:[0,3.2,1.5]},top:{p:[-.01,38,.01],t:[0,3.2,0]},belly:{p:[-11,-8.5,-15],t:[0,2.2,0]},cockpit:{p:[-7,7.5,-13],t:[0,4.4,-4.2]},fan:{p:[-7,9.5,-5],t:[0,4.2,-1.6]}};
const views={exploded:{p:[-13.5,9.8,-16],t:[0,3,0.4]},display:{p:[-13,9.5,-19],t:[0,-.6,-3.2]},hero:{p:[-12,8,-15],t:[0,0,0]},top:{p:[-.01,24,.01],t:[0,0,0]},belly:{p:[-12,-11,-17],t:[0,-.5,0]},cockpit:{p:[-3.3,2.8,-8.7],t:[0,.55,-4.7]},rear:{p:[-4,2,12],t:[0,0,5]},fan:{p:[-3.5,6,-1.9],t:[0,.4,-1.6]}};
const XEXP=[null,{p:[-13.5,9.8,-16],t:[0,3,.4]},{p:[-16.5,11.5,-19],t:[0,3.6,1]},{p:[-21,14,-21.5],t:[0,4.2,.2]}];
function setView(name){const v=name==='exploded'?XEXP[Math.min(3,Math.max(1,Math.round(target.explode)))]:views[name];if(!v)return;floor.visible=grid.visible=name!=='belly';viewTween={start:performance.now(),p:camera.position.clone(),t:orbit.target.clone(),endP:new T.Vector3(...v.p),endT:new T.Vector3(...v.t)};if(target.explode>.5&&XVIEW[name]){viewTween.endP.set(...XVIEW[name].p);viewTween.endT.set(...XVIEW[name].t)}if(name==='exploded'||target.explode>.5&&XVIEW[name]){const k=Math.min(1.95,Math.max(1,1.15*stage.clientHeight/stage.clientWidth)),e=viewTween;e.endP.sub(e.endT).multiplyScalar(k).add(e.endT)}document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name))}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{stopTour();setView(b.dataset.view)});$('#about').onclick=()=>$('#info').showModal();$('#closeInfo').onclick=()=>$('#info').close();
function stopTour(){tour=null;$('#tour').textContent='Guided walkthrough'}$('#tour').onclick=()=>{if(tour){stopTour();return}target={...defaults,paint:target.paint,stores:target.stores,livery:target.livery};tour={start:performance.now(),step:-1};$('#tour').textContent='Stop walkthrough';setView('hero');syncUI()};
const tourSteps=[{view:'hero',v:{},text:'F-35B · Explore the articulated aircraft.'},{view:'cockpit',v:{canopy:1},text:'Forward-opening canopy and detailed cockpit.'},{view:'belly',v:{bay:1,canopy:0},text:'Internal bays with interchangeable inert display stores.'},{view:'fan',v:{bay:0,lift:1},text:'Lift fan, auxiliary doors and downward nozzle configuration.'},{view:'rear',v:{},text:'Artistic representation of the swiveling rear nozzle.'},{view:'hero',v:{lift:0,gear:1,flaps:.6},text:'Coordinated landing gear stow and movable flight controls.'},{view:'hero',v:{gear:0,flaps:0},text:'Back on its gear. Your turn to explore.'}];
let previous=performance.now(),count=0,lastStats=previous;function animate(now){requestAnimationFrame(animate);let dt=Math.min(.05,(now-previous)/1000);previous=now;if(tour){const step=Math.min(tourSteps.length-1,Math.floor((now-tour.start)/5500));if(step!==tour.step){tour.step=step;const x=tourSteps[step];Object.assign(target,x.v);setView(x.view);syncUI();$('#message').textContent=x.text}if(now-tour.start>tourSteps.length*5500)stopTour()}
 for(const k of Object.keys(defaults))if(typeof defaults[k]==='number')state[k]+=((target[k]||0)-state[k])*Math.min(1,dt*5);if($('#fanSpin').checked&&state.lift>.7){spin+=dt*2;state.fan=spin}else state.fan=0;
 applyPose();if(viewTween){const u=Math.min(1,(now-viewTween.start)/950),e=u*u*(3-2*u);camera.position.lerpVectors(viewTween.p,viewTween.endP,e);orbit.target.lerpVectors(viewTween.t,viewTween.endT,e);if(u===1)viewTween=null}panel();drawLabels();orbit.autoRotate=$('#orbit').checked;orbit.autoRotateSpeed=.55;orbit.update();renderer.render(scene,camera);count++;if(now-lastStats>1500){$('#stats').textContent=`${Math.round(count*1000/(now-lastStats))} FPS · ${Math.round(renderer.info.render.triangles/1000)}K TRIANGLES`;count=0;lastStats=now}}
const lampEls=[...document.querySelectorAll('[data-lamp]')],setEls=[...document.querySelectorAll('[data-set]')],colEls=[...document.querySelectorAll('[data-color]')],tabEls=[...document.querySelectorAll('[data-tab-btn]')];
function flag(el,name,v){v=String(v);if(el.getAttribute(name)!==v)el.setAttribute(name,v)}
const xlEls=[...document.querySelectorAll('[data-xl]')];
function panel(){const L={canopy:state.canopy>.02,bay:state.bay>.02,lift:state.lift>.02,transit:state.gear>.02&&state.gear<.98,down:state.gear<=.02,stores:target.loadout==='aircraft'};for(const e of lampEls)flag(e,'data-on',L[e.dataset.lamp]);for(const e of setEls)flag(e,'aria-pressed',target[e.dataset.set]===e.dataset.val);flag($('#explodeKey'),'aria-pressed',target.explode>.5);{const x=$('#xTools'),h=!(target.explode>.02||xAuto);if(x.hidden!==h)x.hidden=h}{const x=$('#xSys'),h=!(target.explode>.02&&xShow);if(x.hidden!==h)x.hidden=h;const s=$('#explode2');if(document.activeElement!==s&&Math.abs(s.value-target.explode)>.005)s.value=target.explode}for(const b of xlEls)flag(b,'aria-pressed',Math.round(target.explode)===Number(b.dataset.xl));{const o=$('#out-explode'),s=target.explode<=0?'Off':'L'+(+target.explode).toFixed(1);if(o.textContent!==s)o.textContent=s}for(const e of colEls)flag(e,'aria-pressed',target.livery==='none'&&String(target.paint).toLowerCase()===e.dataset.color)}
setEls.forEach(b=>b.onclick=()=>{const s=$('#'+b.dataset.set);s.value=b.dataset.val;s.dispatchEvent(new Event('change'))});
tabEls.forEach(b=>b.onclick=()=>{$('#console').dataset.tab=b.dataset.tabBtn;tabEls.forEach(x=>x.setAttribute('aria-pressed',String(x===b)))});
$('#panelToggle').onclick=e=>{const f=document.body.classList.toggle('full');e.currentTarget.setAttribute('aria-pressed',String(!f))};
const dataEl=$('#data'),dtabs=[...document.querySelectorAll('[data-dtab]')];function showData(v){dataEl.hidden=!v;$('#dataToggle').setAttribute('aria-pressed',String(v))}
$('#dataToggle').onclick=()=>showData(dataEl.hidden);showData(innerWidth>=1100);
dtabs.forEach(b=>b.onclick=()=>{dataEl.dataset.tab=b.dataset.dtab;dtabs.forEach(x=>x.setAttribute('aria-pressed',String(x===b)));dataEl.querySelector('.dbody').scrollTop=0});
{const fsb=$('#fsToggle'),de=document.documentElement,req=de.requestFullscreen||de.webkitRequestFullscreen,fse=()=>document.fullscreenElement||document.webkitFullscreenElement;if(!req)fsb.hidden=true;fsb.onclick=()=>{if(fse())(document.exitFullscreen||document.webkitExitFullscreen).call(document);else{const p=req.call(de);if(p&&p.catch)p.catch(()=>{$('#message').textContent='Full screen is not available in this browser.'})}};for(const ev of['fullscreenchange','webkitfullscreenchange'])document.addEventListener(ev,()=>fsb.setAttribute('aria-pressed',String(!!fse())))}
{let was=0;$('#explode').addEventListener('input',e=>{const v=Number(e.target.value);if(v>0&&Math.ceil(v)!==Math.ceil(was))setView('exploded');if(v===0&&was>0)setView('hero');was=v});document.querySelectorAll('[data-xl]').forEach(b=>b.onclick=()=>{stopTour();target.explode=Number(b.dataset.xl);was=target.explode;syncUI();xFrame();$('#message').textContent=['','Level 1: major assemblies.','Level 2: sub-assemblies, engine and drive train lifted out.','Level 3: engine modules, rotors and fittings.'][target.explode]});$('#explodeKey').onclick=()=>{stopTour();const on=target.explode<.5;target.explode=on?1:0;was=target.explode;syncUI();if(on!==document.body.classList.contains('full'))$('#panelToggle').click();xAuto=on&&document.body.classList.contains('full');setView(on?'exploded':'hero');$('#message').textContent=on?'Exploded view: every assembly separated and labelled. Panel brings the controls back.':'Aircraft reassembled.'}}
function xRestore(){xAuto=false;if(document.body.classList.contains('full'))$('#panelToggle').click();$('#message').textContent='Aircraft reassembled.'}
$('#xExit').onclick=()=>{if(target.explode>=.5)$('#explodeKey').click();else{target.explode=0;syncUI();setView('hero');xRestore()}};
$('#explode2').addEventListener('change',e=>{if(Number(e.target.value)<=.02&&xAuto)xRestore()});
$('#panelToggle').addEventListener('click',()=>setTimeout(()=>{if(!document.body.classList.contains('full'))xAuto=false},0));
$('#xLab').onclick=e=>{xShow=!xShow;e.currentTarget.setAttribute('aria-pressed',String(xShow))};
$('#explode2').addEventListener('input',e=>{const s=$('#explode');s.value=e.target.value;s.dispatchEvent(new Event('input',{bubbles:true}))});
requestAnimationFrame(animate);
window.hangar={cam:(p,q)=>{viewTween=null;camera.position.set(...p);orbit.target.set(...q);orbit.update()},snap:()=>{for(const k in target)if(typeof target[k]==='number')state[k]=target[k]},scene,paintMats,getState:()=>({...target}),setState:v=>{for(const [,fields]of defs)for(const[k,,min,max]of fields)if(Number.isFinite(v[k]))target[k]=T.MathUtils.clamp(v[k],min,max);syncUI()},setView,inspect:()=>({rigs:rigs.length,gearTracks:gearNodes.length,actuators:actuators.length,triangles:renderer.info.render.triangles,drawCalls:renderer.info.render.calls})};
