import * as T from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {GLTFLoader} from './vendor/GLTFLoader.js';
import {applyUV,liveryCanvas} from './livery.js?v=4';
const $=s=>document.querySelector(s), stage=$('#stage');
const defs=[['Access & lift system',[['canopy','Canopy',0,1],['bay','Internal bay doors',0,1],['lift','Vertical-lift configuration',0,1]]],['Landing gear',[['gear','Retract gear',0,1],['steering','Nose steering',-1,1],['suspension','Suspension compression',0,1],['wheelspin','Wheel rotation',0,1]]],['Flight controls',[['flaps','Flaps',0,1],['rudders','Rudders',-1,1],['stabilizers','Stabilizers',-1,1]]],['Display',[['explode','Exploded view',0,1]]]];
const defaults={canopy:0,bay:0,lift:0,gear:0,steering:0,suspension:0,wheelspin:0,flaps:0,rudders:0,stabilizers:0,explode:0,fan:0,paint:'#75818c',stores:'training',loadout:'none',livery:'none'};
let state={...defaults}, target={...defaults}, model, tracks={}, rigs=[], gearNodes=[], actuators=[], bySource=new Map(), paintMats=new Set(), tour=null, viewTween=null, spin=0;
for(const [,fields] of defs)for(const [key] of fields)$('#'+key).addEventListener('input',e=>{stopTour();target[key]=Number(e.target.value);syncUI()});
function syncUI(){for(const [,fields] of defs)for(const [k] of fields){$('#'+k).value=target[k];$('#out-'+k).textContent=Math.round(target[k]*100)+'%'}$('#paint').value=target.paint;$('#stores').value=target.stores;$('#loadout').value=target.loadout;$('#livery').value=target.livery}
const renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.9;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;stage.prepend(renderer.domElement);
const scene=new T.Scene();scene.background=new T.Color('#151e23');scene.fog=new T.Fog('#151e23',45,95);
{const c=document.createElement('canvas');c.width=1024;c.height=512;const g=c.getContext('2d'),gr=g.createLinearGradient(0,0,0,512);gr.addColorStop(0,'#c3d0dc');gr.addColorStop(.42,'#6c7a87');gr.addColorStop(.5,'#2a3238');gr.addColorStop(1,'#14191c');g.fillStyle=gr;g.fillRect(0,0,1024,512);g.fillStyle='#ffffff';for(let i=0;i<8;i++)g.fillRect(30+i*128,50,84,26);g.fillStyle='#fff0d2';g.fillRect(160,120,280,56);g.fillStyle='#d6e4ff';g.fillRect(690,140,200,46);const t=new T.CanvasTexture(c);t.mapping=T.EquirectangularReflectionMapping;t.colorSpace=T.SRGBColorSpace;const pm=new T.PMREMGenerator(renderer);scene.environment=pm.fromEquirectangular(t).texture;scene.environmentIntensity=1.1;t.dispose();pm.dispose()}
const camera=new T.PerspectiveCamera(40,1,.05,150);camera.position.set(-12,8,-15);
const orbit=new OrbitControls(camera,renderer.domElement);orbit.target.set(0,0,0);orbit.enableDamping=true;orbit.dampingFactor=.07;orbit.minDistance=2;orbit.maxDistance=45;orbit.maxPolarAngle=Math.PI*.95;orbit.addEventListener('start',()=>{viewTween=null;stopTour()});
scene.add(new T.HemisphereLight('#d8ecff','#64707a',1.5));
const key=new T.DirectionalLight('#fff0d8',2);key.position.set(-8,15,-8);key.castShadow=true;key.shadow.mapSize.set(1024,1024);Object.assign(key.shadow.camera,{left:-13,right:13,top:13,bottom:-13,near:1,far:50});key.shadow.bias=-.001;key.shadow.normalBias=.035;scene.add(key);
const rim=new T.DirectionalLight('#9fbfff',1);rim.position.set(8,6,12);scene.add(rim);const bellyFill=new T.DirectionalLight('#d5dfe6',1.5);bellyFill.position.set(-3,-9,-5);scene.add(bellyFill);
const floor=new T.Mesh(new T.PlaneGeometry(150,150),new T.MeshStandardMaterial({color:'#253137',roughness:.91,envMapIntensity:.25}));floor.rotation.x=-Math.PI/2;floor.position.y=-2.205;floor.receiveShadow=true;scene.add(floor);
const grid=new T.GridHelper(80,40,'#425259','#303e44');grid.position.y=-2.202;grid.material.transparent=true;grid.material.opacity=.25;scene.add(grid);
function stripe(x,z,w,l){const o=new T.Mesh(new T.PlaneGeometry(w,l),new T.MeshBasicMaterial({color:'#a4b58b',transparent:true,opacity:.35}));o.rotation.x=-Math.PI/2;o.position.set(x,-2.199,z);scene.add(o)}for(let z=-11;z<=11;z+=2)stripe(0,z,.055,.8);for(const x of [-6.8,6.8])stripe(x,0,.04,18);
new ResizeObserver(()=>{camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix();renderer.setSize(stage.clientWidth,stage.clientHeight)}).observe(stage);
const basis=new T.Quaternion().setFromAxisAngle(new T.Vector3(1,0,0),-Math.PI/2),basisInv=basis.clone().invert();
const vec=a=>new T.Vector3(a[0],a[2],-a[1]);const quat=a=>basis.clone().multiply(new T.Quaternion(...a)).multiply(basisInv);
function initialize(gltf,poses){model=gltf.scene;scene.add(model);tracks=poses;model.traverse(o=>{if(o.userData.source_name)bySource.set(o.userData.source_name,o);o.userData.rest={p:o.position.clone(),q:o.quaternion.clone(),s:o.scale.clone()};if(o.userData.control)rigs.push(o);if(o.userData.gear_pose&&poses[o.userData.gear_pose])gearNodes.push(o);if(o.userData.actuator_start)actuators.push(o);if(o.isMesh){o.castShadow=true;o.receiveShadow=true;for(const m of (Array.isArray(o.material)?o.material:[o.material])){if(/F35D.*(body|panel|edge|radome)/i.test(m.name)){paintMats.add(m);m.metalness=.55;m.roughness=.52;if(!m.userData.original)m.userData.original=m.color.clone()}if(/glass/i.test(m.name)){m.transparent=true;m.opacity=.33;m.depthWrite=false;m.roughness=.15;m.metalness=.12;if('transmission'in m)m.transmission=0;m.side=T.DoubleSide}}}});applyUV(T,model,paintMats);initExplode();try{let saved=JSON.parse(localStorage.getItem('hangar01-config'));if(saved){for(const [,fields]of defs)for(const[k,,min,max]of fields)if(Number.isFinite(saved[k]))target[k]=T.MathUtils.clamp(saved[k],min,max);if(/^#[0-9a-f]{6}$/i.test(saved.paint))target.paint=saved.paint;if(['training','display','empty'].includes(saved.stores))target.stores=saved.stores;if(['none','aircraft','hangar'].includes(saved.loadout))target.loadout=saved.loadout;if(['none','usaf','usmc'].includes(saved.livery))target.livery=saved.livery}}catch{}state={...target};syncUI();paint(target.paint);if(target.livery!=='none')setLivery(target.livery);applyPose();$('#loading').hidden=true;window.hangarReady=true;$('#message').textContent='Aircraft ready. Drag to explore, or open a mechanism.'}
Promise.all([new GLTFLoader().loadAsync('./assets/f35b-hangar-x.glb'),fetch('./assets/gear-poses.json').then(r=>{if(!r.ok)throw Error('Pose file unavailable');return r.json()})]).then(([g,p])=>initialize(g,p)).catch(e=>{$('#loading').textContent='Unable to load the aircraft. Start the local server, then reload. '+e.message;console.error(e)});
const LIFT=3.2,XV={fuselage:[0,0,0],canopy:[0,.9,2.7],seat:[0,-.2,1.35],wingR:[2.6,0,0],wingL:[-2.6,0,0],tailR:[1.7,-1.9,0],tailL:[-1.7,-1.9,0],finR:[1.3,-.5,1.9],finL:[-1.3,-.5,1.9],liftdoor:[0,0,2.5],fan1:[0,0,1.7],fan2:[0,0,.95],aux:[0,-.3,1.2],exit:[0,0,-1.1],nozzle:[0,-2.1,0],bayR:[.55,0,-1.2],bayL:[-.55,0,-1.2],baystores:[0,0,-2.1],gearN:[0,.7,-1.5],gearR:[1.0,0,-1.5],gearL:[-1.0,0,-1.5],extR:[2.6,0,-1.0],extL:[-2.6,0,-1.0],pod:[0,.4,-2.9]};
const XNAME={fuselage:'Fuselage and inlets',canopy:'Canopy',seat:'Ejection seat',wingR:'Right wing',wingL:'Left wing',tailR:'Right horizontal tail',tailL:'Left horizontal tail',finR:'Right fin and rudder',finL:'Left fin and rudder',liftdoor:'Lift fan door',fan1:'Lift fan, upper stage',fan2:'Lift fan, lower stage',aux:'Auxiliary inlet doors',exit:'Lift fan exit doors',nozzle:'Swivel nozzle',bayR:'Right weapons bay doors',bayL:'Left weapons bay doors',baystores:'Bay stores',gearN:'Nose gear',gearR:'Right main gear',gearL:'Left main gear',extR:'Right wing stores',extL:'Left wing stores',pod:'Gun pod'};
let xNodes=[],xLabels=[];const xTmp=new T.Vector3();
function initExplode(){const boxes={},gearSet=new Set(gearNodes);model.updateMatrixWorld(true);model.traverse(o=>{const g=o.userData.xg;if(!g||!XV[g])return;o.userData.xv=vec([XV[g][0],XV[g][1],XV[g][2]+LIFT]);o.userData.xfree=!o.userData.control&&!gearSet.has(o);xNodes.push(o);(boxes[g]||(boxes[g]={box:new T.Box3(),nodes:[]})).nodes.push(o);boxes[g].box.expandByObject(o)});
 const host=$('#xlabels');for(const g of Object.keys(XV)){const b=boxes[g];if(!b||b.box.isEmpty())continue;const el=document.createElement('div');el.className='xl';el.innerHTML='<span></span>';el.firstChild.textContent=XNAME[g];host.append(el);xLabels.push({el,c:b.box.getCenter(new T.Vector3()),v:vec([XV[g][0],XV[g][1],XV[g][2]+LIFT]),nodes:b.nodes})}}
function shown(o){for(;o;o=o.parent)if(!o.visible)return false;return true}
let xShow=true;function drawLabels(){const ex=state.explode||0,a=xShow?Math.min(1,Math.max(0,(ex-.45)/.35)):0,host=$('#xlabels');if(a<=0){if(!host.hidden)host.hidden=true;return}host.hidden=false;host.style.opacity=a;const w=stage.clientWidth,hh=stage.clientHeight,vis=[];for(const L of xLabels){xTmp.copy(L.c).addScaledVector(L.v,ex).project(camera);const ok=xTmp.z<1&&Math.abs(xTmp.x)<1.05&&Math.abs(xTmp.y)<1.05&&L.nodes.some(shown);L.el.style.display=ok?'':'none';if(!ok)continue;L.x=(xTmp.x+1)/2*w;L.y=(1-xTmp.y)/2*hh;if(!L.w){L.w=L.el.firstChild.offsetWidth;L.hgt=L.el.firstChild.offsetHeight}vis.push(L)}
 vis.sort((p,q)=>q.y-p.y);const placed=[];for(const L of vis){const cx=Math.min(Math.max(L.x,L.w/2+6),Math.max(L.w/2+6,w-L.w/2-6)),l=cx-L.w/2-3,r=cx+L.w/2+3;let h=24;for(let n=0;n<16;n++){const t=L.y-h-2-L.hgt,b=L.y-h-2;if(!placed.some(P=>l<P.r&&r>P.l&&t<P.b+3&&b>P.t-3))break;h+=L.hgt+5}placed.push({l,r,t:L.y-h-2-L.hgt,b:L.y-h-2});L.el.style.setProperty('--h',h+'px');L.el.style.setProperty('--dx',(cx-L.x).toFixed(1)+'px');L.el.style.transform=`translate(${L.x.toFixed(1)}px,${L.y.toFixed(1)}px)`}}
function applyPose(){if(!model)return;for(const o of rigs){const d=o.userData,r=d.rest,v=state[d.control]||0;o.position.copy(r.p);o.quaternion.copy(r.q);if(d.translation?.some(n=>n!==0))o.position.addScaledVector(vec(d.translation),v);if(d.angle)o.quaternion.multiply(new T.Quaternion().setFromAxisAngle(vec(d.axis).normalize(),d.angle*v))}
 for(const o of gearNodes){const frames=tracks[o.userData.gear_pose],u=T.MathUtils.clamp(state.gear,0,1)*(frames.length-1),i=Math.floor(u),j=Math.min(i+1,frames.length-1),t=u-i,a=frames[i],b=frames[j];o.position.copy(vec(a.p).lerp(vec(b.p),t));o.quaternion.copy(quat(a.q).slerp(quat(b.q),t));o.scale.set(a.s[0]+(b.s[0]-a.s[0])*t,a.s[2]+(b.s[2]-a.s[2])*t,a.s[1]+(b.s[1]-a.s[1])*t)}
 {const ex=state.explode||0;for(const o of xNodes){if(o.userData.xfree)o.position.copy(o.userData.rest.p);o.position.addScaledVector(o.userData.xv,ex)}}
 model.updateMatrixWorld(true);for(const o of actuators){const d=o.userData,a=bySource.get(d.actuator_start),b=bySource.get(d.actuator_end);if(!a||!b)continue;let p=a.getWorldPosition(new T.Vector3()),q=b.getWorldPosition(new T.Vector3()),v=q.clone().sub(p),from=p.clone().addScaledVector(v,d.start_fraction);o.parent.worldToLocal(from);o.position.copy(from);let rotation=new T.Quaternion().setFromUnitVectors(new T.Vector3(0,1,0),v.clone().normalize());o.quaternion.copy(o.parent.getWorldQuaternion(new T.Quaternion()).invert().multiply(rotation));o.scale.set(1,v.length()*(d.end_fraction-d.start_fraction),1)}
 model.traverse(o=>{if(o.morphTargetInfluences){let p=o;while(p&&!p.userData.morph_control)p=p.parent;if(p)o.morphTargetInfluences[0]=state[p.userData.morph_control]||0;}if(o.userData.store_set)o.visible=o.userData.store_set===target.stores;if(o.userData.loadout_set)o.visible=o.userData.loadout_set===target.loadout;if(o.userData.hide_when_retracted)o.visible=state.gear<.7;if(o.userData.explode_only)o.visible=(state.explode||0)>.03});model.updateMatrixWorld(true)}
const livTex={};async function setLivery(v){target.livery=v;if(v!=='none'&&!livTex[v]){const t=new T.CanvasTexture(await liveryCanvas(v,innerWidth<900?80:128));t.colorSpace=T.SRGBColorSpace;t.anisotropy=renderer.capabilities.getMaxAnisotropy();livTex[v]=t}paint(target.paint)}
function paint(hex){target.paint=hex;const L=livTex[target.livery]||null;for(const m of paintMats){if(m.map!==L){m.map=L;m.needsUpdate=true}if(L){m.color.set('#ffffff');continue}m.color.set(hex);const lum=m.userData.original?.getHSL({}).l||.2;m.color.multiplyScalar(T.MathUtils.clamp(lum/.18,.65,1.3))}syncUI()}
$('#paint').addEventListener('input',e=>{target.livery='none';paint(e.target.value)});document.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{target.livery='none';paint(b.dataset.color)});$('#livery').onchange=e=>{setLivery(e.target.value);$('#message').textContent=({none:'Plain finish.',usaf:'U.S. Air Force scheme applied.',usmc:'U.S. Marine Corps scheme applied.'})[e.target.value]};$('#stores').onchange=e=>{target.stores=e.target.value;$('#message').textContent='Bay contents changed. Open the internal bay doors to inspect.'};$('#loadout').onchange=e=>{target.loadout=e.target.value;$('#message').textContent=({none:'Clean configuration: no external stores.',aircraft:'Stores loaded on the wing hardpoints and centreline.',hangar:'Stores laid out beside the aircraft.'})[target.loadout];if(target.loadout==='hangar')setView('display')};$('#save').onclick=()=>{try{localStorage.setItem('hangar01-config',JSON.stringify(target));$('#message').textContent='Configuration saved in this browser.'}catch{$('#message').textContent='Browser storage is unavailable.'}};
$('#reset').onclick=()=>{stopTour();target={...defaults};$('#orbit').checked=false;$('#fanSpin').checked=false;paint(target.paint);syncUI();setView('hero');$('#message').textContent='Default configuration restored.'};$('#quality').onchange=e=>{const q=e.target.value;renderer.setPixelRatio(Math.min(devicePixelRatio,q==='high'?2:q==='low'?1:1.5));renderer.shadowMap.enabled=q!=='low';renderer.setSize(stage.clientWidth,stage.clientHeight)};
const XVIEW={rear:{p:[-8,8.5,17],t:[0,3.2,1.5]},top:{p:[-.01,38,.01],t:[0,3.2,0]},belly:{p:[-11,-8.5,-15],t:[0,2.2,0]},cockpit:{p:[-7,7.5,-13],t:[0,4.4,-4.2]},fan:{p:[-7,9.5,-5],t:[0,4.2,-1.6]}};
const views={exploded:{p:[-13.5,9.8,-16],t:[0,3,0.4]},display:{p:[-13,9.5,-19],t:[0,-.6,-3.2]},hero:{p:[-12,8,-15],t:[0,0,0]},top:{p:[-.01,24,.01],t:[0,0,0]},belly:{p:[-12,-11,-17],t:[0,-.5,0]},cockpit:{p:[-3.3,2.8,-8.7],t:[0,.55,-4.7]},rear:{p:[-4,2,12],t:[0,0,5]},fan:{p:[-3.5,6,-1.9],t:[0,.4,-1.6]}};
function setView(name){const v=views[name];if(!v)return;floor.visible=grid.visible=name!=='belly';viewTween={start:performance.now(),p:camera.position.clone(),t:orbit.target.clone(),endP:new T.Vector3(...v.p),endT:new T.Vector3(...v.t)};if(target.explode>.5&&XVIEW[name]){viewTween.endP.set(...XVIEW[name].p);viewTween.endT.set(...XVIEW[name].t)}if(name==='exploded'||target.explode>.5&&XVIEW[name]){const k=Math.min(1.95,Math.max(1,1.15*stage.clientHeight/stage.clientWidth)),e=viewTween;e.endP.sub(e.endT).multiplyScalar(k).add(e.endT)}document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name))}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{stopTour();setView(b.dataset.view)});$('#about').onclick=()=>$('#info').showModal();$('#closeInfo').onclick=()=>$('#info').close();
function stopTour(){tour=null;$('#tour').textContent='Guided walkthrough'}$('#tour').onclick=()=>{if(tour){stopTour();return}target={...defaults,paint:target.paint,stores:target.stores,livery:target.livery};tour={start:performance.now(),step:-1};$('#tour').textContent='Stop walkthrough';setView('hero');syncUI()};
const tourSteps=[{view:'hero',v:{},text:'F-35B · Explore the articulated aircraft.'},{view:'cockpit',v:{canopy:1},text:'Forward-opening canopy and detailed cockpit.'},{view:'belly',v:{bay:1,canopy:0},text:'Internal bays with interchangeable inert display stores.'},{view:'fan',v:{bay:0,lift:1},text:'Lift fan, auxiliary doors and downward nozzle configuration.'},{view:'rear',v:{},text:'Artistic representation of the swiveling rear nozzle.'},{view:'hero',v:{lift:0,gear:1,flaps:.6},text:'Coordinated landing gear stow and movable flight controls.'},{view:'hero',v:{gear:0,flaps:0},text:'Back on its gear. Your turn to explore.'}];
let previous=performance.now(),count=0,lastStats=previous;function animate(now){requestAnimationFrame(animate);let dt=Math.min(.05,(now-previous)/1000);previous=now;if(tour){const step=Math.min(tourSteps.length-1,Math.floor((now-tour.start)/5500));if(step!==tour.step){tour.step=step;const x=tourSteps[step];Object.assign(target,x.v);setView(x.view);syncUI();$('#message').textContent=x.text}if(now-tour.start>tourSteps.length*5500)stopTour()}
 for(const k of Object.keys(defaults))if(typeof defaults[k]==='number')state[k]+=((target[k]||0)-state[k])*Math.min(1,dt*5);if($('#fanSpin').checked&&state.lift>.7){spin+=dt*2;state.fan=spin}else state.fan=0;
 applyPose();if(viewTween){const u=Math.min(1,(now-viewTween.start)/950),e=u*u*(3-2*u);camera.position.lerpVectors(viewTween.p,viewTween.endP,e);orbit.target.lerpVectors(viewTween.t,viewTween.endT,e);if(u===1)viewTween=null}panel();drawLabels();orbit.autoRotate=$('#orbit').checked;orbit.autoRotateSpeed=.55;orbit.update();renderer.render(scene,camera);count++;if(now-lastStats>1500){$('#stats').textContent=`${Math.round(count*1000/(now-lastStats))} FPS · ${Math.round(renderer.info.render.triangles/1000)}K TRIANGLES`;count=0;lastStats=now}}
const lampEls=[...document.querySelectorAll('[data-lamp]')],setEls=[...document.querySelectorAll('[data-set]')],colEls=[...document.querySelectorAll('[data-color]')],tabEls=[...document.querySelectorAll('[data-tab-btn]')];
function flag(el,name,v){v=String(v);if(el.getAttribute(name)!==v)el.setAttribute(name,v)}
function panel(){const L={canopy:state.canopy>.02,bay:state.bay>.02,lift:state.lift>.02,transit:state.gear>.02&&state.gear<.98,down:state.gear<=.02,stores:target.loadout==='aircraft'};for(const e of lampEls)flag(e,'data-on',L[e.dataset.lamp]);for(const e of setEls)flag(e,'aria-pressed',target[e.dataset.set]===e.dataset.val);flag($('#explodeKey'),'aria-pressed',target.explode>.5);{const x=$('#xTools'),h=!(target.explode>.02);if(x.hidden!==h)x.hidden=h}for(const e of colEls)flag(e,'aria-pressed',target.livery==='none'&&String(target.paint).toLowerCase()===e.dataset.color)}
setEls.forEach(b=>b.onclick=()=>{const s=$('#'+b.dataset.set);s.value=b.dataset.val;s.dispatchEvent(new Event('change'))});
tabEls.forEach(b=>b.onclick=()=>{$('#console').dataset.tab=b.dataset.tabBtn;tabEls.forEach(x=>x.setAttribute('aria-pressed',String(x===b)))});
$('#panelToggle').onclick=e=>{const f=document.body.classList.toggle('full');e.currentTarget.setAttribute('aria-pressed',String(!f))};
const dataEl=$('#data'),dtabs=[...document.querySelectorAll('[data-dtab]')];function showData(v){dataEl.hidden=!v;$('#dataToggle').setAttribute('aria-pressed',String(v))}
$('#dataToggle').onclick=()=>showData(dataEl.hidden);showData(innerWidth>=1100);
dtabs.forEach(b=>b.onclick=()=>{dataEl.dataset.tab=b.dataset.dtab;dtabs.forEach(x=>x.setAttribute('aria-pressed',String(x===b)));dataEl.querySelector('.dbody').scrollTop=0});
{const fsb=$('#fsToggle'),de=document.documentElement,req=de.requestFullscreen||de.webkitRequestFullscreen,fse=()=>document.fullscreenElement||document.webkitFullscreenElement;if(!req)fsb.hidden=true;fsb.onclick=()=>{if(fse())(document.exitFullscreen||document.webkitExitFullscreen).call(document);else{const p=req.call(de);if(p&&p.catch)p.catch(()=>{$('#message').textContent='Full screen is not available in this browser.'})}};for(const ev of['fullscreenchange','webkitfullscreenchange'])document.addEventListener(ev,()=>fsb.setAttribute('aria-pressed',String(!!fse())))}
{let was=0;$('#explode').addEventListener('input',e=>{const v=Number(e.target.value);if(v>0&&was===0)setView('exploded');if(v===0&&was>0)setView('hero');was=v});$('#explodeKey').onclick=()=>{stopTour();const on=target.explode<.5;target.explode=on?1:0;was=target.explode;syncUI();if(on!==document.body.classList.contains('full'))$('#panelToggle').click();setView(on?'exploded':'hero');$('#message').textContent=on?'Exploded view: every assembly separated and labelled. Panel brings the controls back.':'Aircraft reassembled.'}}
$('#xExit').onclick=()=>$('#explodeKey').click();
$('#xLab').onclick=e=>{xShow=!xShow;e.currentTarget.setAttribute('aria-pressed',String(xShow))};
requestAnimationFrame(animate);
window.hangar={scene,paintMats,getState:()=>({...target}),setState:v=>{for(const [,fields]of defs)for(const[k,,min,max]of fields)if(Number.isFinite(v[k]))target[k]=T.MathUtils.clamp(v[k],min,max);syncUI()},setView,inspect:()=>({rigs:rigs.length,gearTracks:gearNodes.length,actuators:actuators.length,triangles:renderer.info.render.triangles,drawCalls:renderer.info.render.calls})};
